---

- name: Setup JupyterHub
  hosts: hosts
  remote_user: root

  tasks:
  
  - name: Install web server
    ansible.builtin.package:
      name: nginx
      state: latest

  - name: Nginx Dashboard site configuration
    ansible.builtin.template:
      src: nginx/dashboard.conf
      dest: /etc/nginx/sites-available/dashboard
      owner: root
      group: root
      mode: '0644'
      force: no

  - name: Nginx Dashboard site activation
    ansible.builtin.file:
      src: /etc/nginx/sites-available/dashboard
      dest: /etc/nginx/sites-enabled/dashboard
      owner: root
      group: root
      state: link

  - name: Nginx JupyterHub site configuration
    ansible.builtin.template:
      src: nginx/jupyterhub.conf
      dest: /etc/nginx/sites-available/jupyter
      owner: root
      group: root
      mode: '0644'
      force: no

  - name: Nginx JupyterHub site activation
    ansible.builtin.file:
      src: /etc/nginx/sites-available/jupyter
      dest: /etc/nginx/sites-enabled/jupyter
      owner: root
      group: root
      state: link

  - name: Install Certbot for Nginx
    ansible.builtin.package:
      name: python3-certbot-nginx
      state: latest

  - name: Configure Let's Encrypt certificate
    ansible.builtin.command:
      cmd: certbot --nginx --redirect -d jupyter.pfe.rs -d dashboard.pfe.rs --non-interactive --agree-tos -m admin@pfe.rs
      creates: /etc/letsencrypt/live/jupyter.pfe.rs/privkey.pem
      
  - name: Install Docker
    ansible.builtin.package:
      name: 
        - docker.io
        - python3-docker
      state: latest

  - name: Install Git
    ansible.builtin.package:
      name: git
      state: latest

  - name: Checkout Testbench from GitHib
    ansible.builtin.git:
      repo: git@github.com:pfe-petnica/jupyter-testbench.git
      dest: /srv/testbench

  - name: Build Dashboard container
    community.docker.docker_image:
      name: dashboard
      build:
        path: /srv/testbench
        args:
          listen_port: 8002
          restart: always
      source: build

  - name: Start Dashboard container
    community.docker.docker_container:
      name: dashboard
      image: dashboard
      state: started
      ports:
      - "8002:80"
